// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace App.Core.Models
{
    [Index(nameof(Url), Name = "IX_Artical", IsUnique = true)]
    public partial class Articals
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(80)]
        public string Photo { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [StringLength(80)]
        public string SubTitle { get; set; }
        public string Description { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed ,Enter Like This article-name")]
        public string Url { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime ArticalDate { get; set; }
        public int? DisplayOrder { get; set; }
    }
}