// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace App.Core.Models
{
    public partial class ArticleCategory
    {
        public ArticleCategory()
        {
            Articals = new HashSet<Articals>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int? DisplayOrder { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Articals> Articals { get; set; }
    }
}