// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace App.Core.Models
{
    [Index(nameof(Url), Name = "IX_Product", IsUnique = true)]
    public partial class Product
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed ,Enter Like This product-name")]
        public string Url { get; set; }
        public int CategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal Price { get; set; }
        [StringLength(90)]
        public string SubTitle { get; set; }
        [StringLength(300)]
        public string Description { get; set; }
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public bool IsActive { get; set; }
        public int? DisplayOrder { get; set; }
        [Required]
        [StringLength(80)]
        public string Photo { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(ProductCategory.Product))]
        public virtual ProductCategory Category { get; set; }
    }
}