// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace App.Core.Models
{
    public partial class Subscriptions
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(70)]
        public string Email { get; set; }
        [StringLength(50)]
        public string SubscriptionDate { get; set; }
    }
}